import type { Book, SamplePortfolio } from "./types";

export const BOOKS: Book[] = [
  {
    id: "narrative-numbers",
    title: "Narrative and Numbers",
    author: "Aswath Damodaran",
    year: 2017,
    why: "Forces every holding to name its story, then ask whether the numbers can carry that story. The house text for this tool.",
    challenges: ["tech-optimism", "abundance"],
    ifYouAreHeavyIn: ["ai-platform", "cheap-money-duration", "energy-transition"],
  },
  {
    id: "little-valuation",
    title: "The Little Book of Valuation",
    author: "Aswath Damodaran",
    year: 2011,
    why: "A reminder that price is not value, and that growth is not a personality trait. It is an assumption with a cost of capital attached.",
    challenges: ["tech-optimism"],
    ifYouAreHeavyIn: ["ai-platform", "software-subscription"],
  },
  {
    id: "essays-buffett",
    title: "The Essays of Warren Buffett",
    author: "Lawrence Cunningham (ed.)",
    year: 1997,
    why: "Owner earnings, circle of competence, and why activity is not a virtue. Read it when you feel the itch to reshuffle.",
    challenges: ["financialization"],
    ifYouAreHeavyIn: ["us-exceptionalism", "consumer-brand"],
  },
  {
    id: "poor-charlie",
    title: "Poor Charlie's Almanack",
    author: "Charlie Munger",
    year: 2005,
    why: "Mental models as diversification: you cannot hold one professional deformation and call it a worldview.",
    challenges: ["tech-optimism", "financialization"],
    ifYouAreHeavyIn: ["ai-platform", "payments-rails"],
  },
  {
    id: "hedgehog-fox",
    title: "The Hedgehog and the Fox",
    author: "Isaiah Berlin",
    year: 1953,
    why: "The hedgehog knows one big thing. The fox knows many. Most portfolios are hedgehogs wearing a fox costume of many tickers.",
    challenges: ["tech-optimism", "american-fortress"],
    ifYouAreHeavyIn: ["ai-platform", "fossil-endurance", "energy-transition"],
  },
  {
    id: "righteous-mind",
    title: "The Righteous Mind",
    author: "Jonathan Haidt",
    year: 2012,
    why: "Partisans do not just vote together. They moralize together. Portfolios quietly moralize too: they overweight the industries their tribe already likes.",
    challenges: ["industrial-policy", "american-fortress", "abundance"],
    ifYouAreHeavyIn: ["energy-transition", "fossil-endurance", "defense-multipolar"],
  },
  {
    id: "uncivil-agreement",
    title: "Uncivil Agreement",
    author: "Lilliana Mason",
    year: 2018,
    why: "Identities stack. Once party, class, media, and profession line up, beliefs stop being independent. So do stock picks.",
    challenges: ["american-fortress", "tech-optimism"],
    ifYouAreHeavyIn: ["us-exceptionalism", "ai-platform"],
  },
  {
    id: "political-tribes",
    title: "Political Tribes",
    author: "Amy Chua",
    year: 2018,
    why: "Humans need groups. Markets pretend they do not. A concentrated political exposure is often just tribal belonging with a brokerage account.",
    challenges: ["american-fortress", "global-consumer"],
    ifYouAreHeavyIn: ["defense-multipolar", "china-coupling"],
  },
  {
    id: "superforecasting",
    title: "Superforecasting",
    author: "Philip Tetlock & Dan Gardner",
    year: 2015,
    why: "Foxes beat hedgehogs at prediction. If your book is one thesis, you are volunteering to be the hedgehog Tetlock keeps beating.",
    challenges: ["tech-optimism", "industrial-policy"],
    ifYouAreHeavyIn: ["ai-platform", "energy-transition", "defense-multipolar"],
  },
  {
    id: "thinking-fast",
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    year: 2011,
    why: "Narrative fallacies love a clean story. Valuation is the slow system. Your brokerage app is the fast one.",
    challenges: ["tech-optimism"],
    ifYouAreHeavyIn: ["ai-platform", "cheap-money-duration"],
  },
  {
    id: "antifragile",
    title: "Antifragile",
    author: "Nassim Nicholas Taleb",
    year: 2012,
    why: "A portfolio that only works in one regime is fragile, even if every name inside it looks high quality.",
    challenges: ["financialization", "tech-optimism"],
    ifYouAreHeavyIn: ["cheap-money-duration", "ai-platform"],
  },
  {
    id: "how-world-works",
    title: "How the World Really Works",
    author: "Vaclav Smil",
    year: 2022,
    why: "Energy, food, ammonia, steel. A software-only book of the world is a children's book. Smil is the adult in the room.",
    challenges: ["tech-optimism", "abundance"],
    ifYouAreHeavyIn: ["ai-platform", "software-subscription", "energy-transition"],
  },
  {
    id: "chip-war",
    title: "Chip War",
    author: "Chris Miller",
    year: 2022,
    why: "Semiconductors are not a sector. They are a map. If you own the AI stack, you already own Taiwan risk.",
    challenges: ["tech-optimism", "industrial-policy"],
    ifYouAreHeavyIn: ["ai-platform", "china-coupling"],
  },
  {
    id: "abundance",
    title: "Abundance",
    author: "Ezra Klein & Derek Thompson",
    year: 2025,
    why: "A left-coded case that the bottleneck is building. Useful if your politics and your energy names are not on speaking terms.",
    challenges: ["hard-assets", "american-fortress"],
    ifYouAreHeavyIn: ["energy-transition", "reindustrialization"],
  },
  {
    id: "why-nations-fail",
    title: "Why Nations Fail",
    author: "Daron Acemoglu & James Robinson",
    year: 2012,
    why: "Institutions are the discount rate. Country risk is not a vibe; it is extractive versus inclusive rules.",
    challenges: ["global-consumer", "american-fortress"],
    ifYouAreHeavyIn: ["china-coupling", "us-exceptionalism"],
  },
  {
    id: "dictators-handbook",
    title: "The Dictator's Handbook",
    author: "Bruce Bueno de Mesquita & Alastair Smith",
    year: 2011,
    why: "Selectorate theory: leaders keep the coalition that keeps them in power. Policy risk in a stock is often just that coalition's grocery list.",
    challenges: ["industrial-policy", "american-fortress"],
    ifYouAreHeavyIn: ["defense-multipolar", "energy-transition", "fossil-endurance"],
  },
  {
    id: "price-of-time",
    title: "The Price of Time",
    author: "Edward Chancellor",
    year: 2022,
    why: "Interest rates are a moral and political choice, not a weather report. Duration is a hidden partisan exposure.",
    challenges: ["financialization", "tech-optimism"],
    ifYouAreHeavyIn: ["cheap-money-duration", "software-subscription"],
  },
  {
    id: "changing-world-order",
    title: "Principles for Dealing with the Changing World Order",
    author: "Ray Dalio",
    year: 2021,
    why: "Cycles of reserve currency, debt, and internal conflict. Read skeptically, then ask whether your book assumes the last order is permanent.",
    challenges: ["american-fortress", "financialization"],
    ifYouAreHeavyIn: ["us-exceptionalism", "payments-rails"],
  },
  {
    id: "range",
    title: "Range",
    author: "David Epstein",
    year: 2019,
    why: "Generalists beat specialists in wicked domains. Investing is wicked. A single-industry identity is a career, not a portfolio.",
    challenges: ["tech-optimism"],
    ifYouAreHeavyIn: ["ai-platform", "healthcare-aging"],
  },
  {
    id: "capital-returns",
    title: "Capital Returns",
    author: "Edward Chancellor (ed.)",
    year: 2015,
    why: "The capital cycle: too much money in a beloved story is the risk. AI, green, and fortress trades can all overbuild.",
    challenges: ["industrial-policy", "tech-optimism"],
    ifYouAreHeavyIn: ["ai-platform", "energy-transition", "reindustrialization"],
  },
];

export const SAMPLES: SamplePortfolio[] = [
  {
    id: "consensus",
    name: "The Consensus",
    epithet: "Many tickers, one sermon",
    thesis:
      "What a well-read, well-paid, coastal portfolio looks like in 2026: intelligence as infrastructure, duration as destiny.",
    holdings: [
      { ticker: "NVDA", weight: 22 },
      { ticker: "MSFT", weight: 18 },
      { ticker: "AAPL", weight: 14 },
      { ticker: "GOOGL", weight: 12 },
      { ticker: "AMZN", weight: 12 },
      { ticker: "META", weight: 12 },
      { ticker: "AVGO", weight: 10 },
    ],
  },
  {
    id: "hydrocarbon",
    name: "The Hydrocarbon",
    epithet: "A worldview you can smell",
    thesis:
      "The transition is a brochure. Barrels, yellow iron, and dividends are the adult economy.",
    holdings: [
      { ticker: "XOM", weight: 28 },
      { ticker: "CVX", weight: 22 },
      { ticker: "COP", weight: 18 },
      { ticker: "CAT", weight: 18 },
      { ticker: "DE", weight: 14 },
    ],
  },
  {
    id: "omaha",
    name: "The Omaha Letter",
    epithet: "Brands, tolls, and time",
    thesis:
      "Wonderful businesses, understandable cash, and a willingness to look concentrated in quality rather than in a news cycle.",
    holdings: [
      { ticker: "AAPL", weight: 22 },
      { ticker: "AXP", weight: 14 },
      { ticker: "KO", weight: 12 },
      { ticker: "V", weight: 12 },
      { ticker: "COST", weight: 12 },
      { ticker: "JPM", weight: 10 },
      { ticker: "BRK.B", weight: 18 },
    ],
  },
  {
    id: "fortress",
    name: "The Fortress",
    epithet: "A harder map",
    thesis:
      "Tariffs, arsenals, domestic energy, and suspicion of the last thirty years of globalization.",
    holdings: [
      { ticker: "LMT", weight: 18 },
      { ticker: "RTX", weight: 16 },
      { ticker: "XOM", weight: 16 },
      { ticker: "CAT", weight: 16 },
      { ticker: "FSLR", weight: 12 },
      { ticker: "DE", weight: 12 },
      { ticker: "JPM", weight: 10 },
    ],
  },
  {
    id: "transition",
    name: "The Timetable",
    epithet: "Policy as a cash-flow",
    thesis:
      "The state will force the energy system onto a clock, and the winners are the ones already standing in line for the subsidy.",
    holdings: [
      { ticker: "TSLA", weight: 22 },
      { ticker: "NEE", weight: 20 },
      { ticker: "FSLR", weight: 18 },
      { ticker: "FCX", weight: 16 },
      { ticker: "NVO", weight: 12 },
      { ticker: "PLD", weight: 12 },
    ],
  },
  {
    id: "fox",
    name: "A Fox",
    epithet: "Stories that cannot all be true",
    thesis:
      "Not a free lunch — a refusal to let one book of the world set the entire discount rate. Some of these names will look foolish. That is the point.",
    holdings: [
      { ticker: "MSFT", weight: 12 },
      { ticker: "KO", weight: 10 },
      { ticker: "XOM", weight: 10 },
      { ticker: "NEE", weight: 10 },
      { ticker: "LMT", weight: 10 },
      { ticker: "NVO", weight: 10 },
      { ticker: "CAT", weight: 10 },
      { ticker: "V", weight: 10 },
      { ticker: "TSM", weight: 9 },
      { ticker: "NEM", weight: 9 },
    ],
  },
];
