import type { Company } from "./types";

export const COMPANIES: Company[] = [
  {
    ticker: "NVDA",
    name: "NVIDIA",
    sector: "Technology",
    geography: "United States",
    summary: "The pick-and-shovel of the intelligence buildout.",
    narratives: [
      { id: "ai-platform", weight: 0.7 },
      { id: "cheap-money-duration", weight: 0.2 },
      { id: "us-exceptionalism", weight: 0.1 },
    ],
    philosophies: ["tech-optimism", "abundance", "industrial-policy"],
    policy: { climate: 0.1, defense: 0.25, trade: 0.2, techReg: 0.55, china: 0.45, rates: 0.7 },
    buffett: {
      moat: 4,
      understandability: 2,
      quality: 5,
      note: "A wonderful business whose story changes faster than an annual letter.",
    },
    damodaran: {
      story: "AI infrastructure remains scarce and NVIDIA keeps the toll.",
      risk: "The story is growth at a price that assumes no mean reversion in margins or demand.",
    },
  },
  {
    ticker: "MSFT",
    name: "Microsoft",
    sector: "Technology",
    geography: "United States",
    summary: "Enterprise software, cloud, and a front-row seat to AI distribution.",
    narratives: [
      { id: "ai-platform", weight: 0.4 },
      { id: "software-subscription", weight: 0.45 },
      { id: "us-exceptionalism", weight: 0.15 },
    ],
    philosophies: ["tech-optimism", "moat-compounder", "financialization"],
    policy: { climate: 0.05, defense: 0.15, trade: 0.25, techReg: 0.5, china: 0.2, rates: 0.45 },
    buffett: {
      moat: 5,
      understandability: 3,
      quality: 5,
      note: "Switching costs and distribution that Munger would have recognized as a castle.",
    },
    damodaran: {
      story: "Installed base becomes the channel for intelligence.",
      risk: "Paying software multiples for an AI story that still has to show up in price.",
    },
  },
  {
    ticker: "AAPL",
    name: "Apple",
    sector: "Technology",
    geography: "United States",
    summary: "A consumer religion with a hardware storefront and a services annex.",
    narratives: [
      { id: "consumer-brand", weight: 0.45 },
      { id: "us-exceptionalism", weight: 0.25 },
      { id: "china-coupling", weight: 0.2 },
      { id: "ai-platform", weight: 0.1 },
    ],
    philosophies: ["moat-compounder", "global-consumer", "tech-optimism"],
    policy: { climate: 0.05, defense: 0, trade: 0.35, techReg: 0.4, china: 0.65, rates: 0.25 },
    buffett: {
      moat: 5,
      understandability: 4,
      quality: 5,
      note: "Brand, habit, and a closed garden. The China factory is the un-Buffett part.",
    },
    damodaran: {
      story: "Services deepen the moat after hardware unit growth slows.",
      risk: "A China-coupled consumer story dressed up as a domestic compounder.",
    },
  },
  {
    ticker: "GOOGL",
    name: "Alphabet",
    sector: "Technology",
    geography: "United States",
    summary: "Search rent, YouTube, cloud, and a research lab that might eat the rent.",
    narratives: [
      { id: "ai-platform", weight: 0.4 },
      { id: "software-subscription", weight: 0.2 },
      { id: "us-exceptionalism", weight: 0.2 },
      { id: "cheap-money-duration", weight: 0.2 },
    ],
    philosophies: ["tech-optimism", "financialization", "abundance"],
    policy: { climate: 0.05, defense: 0.1, trade: 0.3, techReg: 0.75, china: 0.05, rates: 0.4 },
    buffett: {
      moat: 4,
      understandability: 3,
      quality: 4,
      note: "An advertising tollbooth whose durability is the open question of the decade.",
    },
    damodaran: {
      story: "Distribution of intent survives the jump from links to models.",
      risk: "Antitrust and AI both attack the same cash cow.",
    },
  },
  {
    ticker: "AMZN",
    name: "Amazon",
    sector: "Consumer",
    geography: "United States",
    summary: "Logistics as a weapon, plus the cloud that bills the rest of the internet.",
    narratives: [
      { id: "us-exceptionalism", weight: 0.3 },
      { id: "ai-platform", weight: 0.25 },
      { id: "consumer-brand", weight: 0.2 },
      { id: "software-subscription", weight: 0.25 },
    ],
    philosophies: ["tech-optimism", "abundance", "global-consumer"],
    policy: { climate: 0.1, defense: 0.05, trade: 0.45, techReg: 0.55, china: 0.15, rates: 0.45 },
    buffett: {
      moat: 4,
      understandability: 3,
      quality: 4,
      note: "Scale economics in retail and a real cash engine in AWS.",
    },
    damodaran: {
      story: "Two stories in one ticker: retail grind and cloud leverage.",
      risk: "A conglomerate discount hiding inside a growth multiple.",
    },
  },
  {
    ticker: "META",
    name: "Meta",
    sector: "Technology",
    geography: "United States",
    summary: "Attention, advertising, and a second bet on whatever comes after phones.",
    narratives: [
      { id: "ai-platform", weight: 0.35 },
      { id: "consumer-brand", weight: 0.25 },
      { id: "cheap-money-duration", weight: 0.25 },
      { id: "us-exceptionalism", weight: 0.15 },
    ],
    philosophies: ["tech-optimism", "financialization"],
    policy: { climate: 0, defense: 0, trade: 0.2, techReg: 0.8, china: 0.05, rates: 0.5 },
    buffett: {
      moat: 3,
      understandability: 3,
      quality: 3,
      note: "Network effects with a habit of lighting cash on fire for the next platform.",
    },
    damodaran: {
      story: "Reels and models defend the ad monopoly; Reality Labs is optionality.",
      risk: "Regulation and a metaverse hangover can both be priced as if they were one story.",
    },
  },
  {
    ticker: "AVGO",
    name: "Broadcom",
    sector: "Technology",
    geography: "United States",
    summary: "Custom silicon and infrastructure software for the same AI buildout.",
    narratives: [
      { id: "ai-platform", weight: 0.6 },
      { id: "software-subscription", weight: 0.25 },
      { id: "us-exceptionalism", weight: 0.15 },
    ],
    philosophies: ["tech-optimism", "financialization"],
    policy: { climate: 0, defense: 0.2, trade: 0.15, techReg: 0.35, china: 0.3, rates: 0.4 },
    buffett: {
      moat: 4,
      understandability: 2,
      quality: 4,
      note: "Customer captivity in custom chips. The leverage is not for the faint of heart.",
    },
    damodaran: {
      story: "AI custom silicon plus a software roll-up.",
      risk: "Two stories, one multiple, a lot of debt.",
    },
  },
  {
    ticker: "TSM",
    name: "TSMC",
    sector: "Technology",
    geography: "Taiwan",
    summary: "The most important factory in the world, sitting on a geopolitical fault.",
    narratives: [
      { id: "ai-platform", weight: 0.45 },
      { id: "china-coupling", weight: 0.25 },
      { id: "reindustrialization", weight: 0.2 },
      { id: "defense-multipolar", weight: 0.1 },
    ],
    philosophies: ["tech-optimism", "industrial-policy", "hard-assets"],
    policy: { climate: 0.05, defense: 0.55, trade: 0.4, techReg: 0.1, china: 0.7, rates: 0.2 },
    buffett: {
      moat: 5,
      understandability: 3,
      quality: 5,
      note: "A real moat with a real map problem.",
    },
    damodaran: {
      story: "Process leadership remains scarce.",
      risk: "Country risk that a sector chart will not show you.",
    },
  },
  {
    ticker: "ASML",
    name: "ASML",
    sector: "Technology",
    geography: "Netherlands",
    summary: "The only company that sells the machines that make the leading chips.",
    narratives: [
      { id: "ai-platform", weight: 0.5 },
      { id: "reindustrialization", weight: 0.2 },
      { id: "china-coupling", weight: 0.2 },
      { id: "cheap-money-duration", weight: 0.1 },
    ],
    philosophies: ["tech-optimism", "industrial-policy", "hard-assets"],
    policy: { climate: 0, defense: 0.3, trade: 0.25, techReg: 0.05, china: 0.55, rates: 0.3 },
    buffett: {
      moat: 5,
      understandability: 2,
      quality: 5,
      note: "A monopoly on a tool. Export control is the political hair on the moat.",
    },
    damodaran: {
      story: "EUV remains a chokepoint.",
      risk: "Geopolitics can close the customer set overnight.",
    },
  },
  {
    ticker: "TSLA",
    name: "Tesla",
    sector: "Consumer",
    geography: "United States",
    summary: "Cars as a software story, energy as a sideline, personality as a factor.",
    narratives: [
      { id: "energy-transition", weight: 0.45 },
      { id: "ai-platform", weight: 0.3 },
      { id: "cheap-money-duration", weight: 0.25 },
    ],
    philosophies: ["tech-optimism", "abundance", "industrial-policy"],
    policy: { climate: 0.75, defense: 0.05, trade: 0.2, techReg: 0.2, china: 0.45, rates: 0.65 },
    buffett: {
      moat: 2,
      understandability: 2,
      quality: 2,
      note: "A story stock. Buffett would want the owner, not the narrative.",
    },
    damodaran: {
      story: "Robotaxi plus energy plus manufacturing scale.",
      risk: "Several optionalities priced as if they were already cash.",
    },
  },
  {
    ticker: "XOM",
    name: "Exxon Mobil",
    sector: "Energy",
    geography: "United States",
    summary: "The remaining supermajor as a cash machine and a political Rorschach.",
    narratives: [
      { id: "fossil-endurance", weight: 0.7 },
      { id: "us-exceptionalism", weight: 0.15 },
      { id: "commodity-cycle", weight: 0.15 },
    ],
    philosophies: ["hard-assets", "american-fortress"],
    policy: { climate: -0.85, defense: 0.15, trade: 0.1, techReg: 0, china: 0.1, rates: -0.1 },
    buffett: {
      moat: 3,
      understandability: 4,
      quality: 4,
      note: "A business you can explain. The terminal value is the argument.",
    },
    damodaran: {
      story: "Oil demand peaks later than the transition slide says.",
      risk: "A political story wearing a commodity costume.",
    },
  },
  {
    ticker: "CVX",
    name: "Chevron",
    sector: "Energy",
    geography: "United States",
    summary: "Upstream cash, dividends, and a slower-transition wager.",
    narratives: [
      { id: "fossil-endurance", weight: 0.7 },
      { id: "commodity-cycle", weight: 0.2 },
      { id: "us-exceptionalism", weight: 0.1 },
    ],
    philosophies: ["hard-assets", "american-fortress"],
    policy: { climate: -0.8, defense: 0.1, trade: 0.1, techReg: 0, china: 0.1, rates: -0.1 },
    buffett: {
      moat: 3,
      understandability: 4,
      quality: 4,
      note: "Owner earnings you can count. Policy you cannot.",
    },
    damodaran: {
      story: "Capital discipline plus lingering oil demand.",
      risk: "Transition policy is a discount-rate event, not a PR event.",
    },
  },
  {
    ticker: "COP",
    name: "ConocoPhillips",
    sector: "Energy",
    geography: "United States",
    summary: "A purer upstream bet on the same hydrocarbon clock.",
    narratives: [
      { id: "fossil-endurance", weight: 0.75 },
      { id: "commodity-cycle", weight: 0.25 },
    ],
    philosophies: ["hard-assets"],
    policy: { climate: -0.8, defense: 0.1, trade: 0.05, techReg: 0, china: 0.05, rates: -0.15 },
    buffett: {
      moat: 2,
      understandability: 4,
      quality: 3,
      note: "Understandable. Cyclical. Not a castle.",
    },
    damodaran: {
      story: "Shale and global barrels still set the price of civilization.",
      risk: "High operating leverage to a single commodity story.",
    },
  },
  {
    ticker: "NEE",
    name: "NextEra Energy",
    sector: "Utilities",
    geography: "United States",
    summary: "Regulated cash plus a long-duration bet that the grid becomes electric.",
    narratives: [
      { id: "energy-transition", weight: 0.65 },
      { id: "cheap-money-duration", weight: 0.25 },
      { id: "us-exceptionalism", weight: 0.1 },
    ],
    philosophies: ["industrial-policy", "abundance", "hard-assets"],
    policy: { climate: 0.8, defense: 0, trade: 0.05, techReg: 0, china: 0, rates: 0.7 },
    buffett: {
      moat: 3,
      understandability: 3,
      quality: 3,
      note: "A utility with a growth story stapled on. Rates are a silent partner.",
    },
    damodaran: {
      story: "America electrifies and NextEra builds the plants.",
      risk: "Duration dressed as a green inevitability.",
    },
  },
  {
    ticker: "FSLR",
    name: "First Solar",
    sector: "Energy",
    geography: "United States",
    summary: "Domestic panels as an industrial-policy instrument.",
    narratives: [
      { id: "energy-transition", weight: 0.55 },
      { id: "reindustrialization", weight: 0.45 },
    ],
    philosophies: ["industrial-policy", "abundance", "american-fortress"],
    policy: { climate: 0.85, defense: 0.05, trade: -0.4, techReg: 0, china: -0.35, rates: 0.4 },
    buffett: {
      moat: 2,
      understandability: 3,
      quality: 3,
      note: "The moat is partly a statute.",
    },
    damodaran: {
      story: "US content rules keep Chinese panels from winning.",
      risk: "A political cash flow with a solar multiple.",
    },
  },
  {
    ticker: "CAT",
    name: "Caterpillar",
    sector: "Industrials",
    geography: "United States",
    summary: "Yellow iron for mines, roads, and whoever is still building.",
    narratives: [
      { id: "reindustrialization", weight: 0.4 },
      { id: "commodity-cycle", weight: 0.35 },
      { id: "us-exceptionalism", weight: 0.25 },
    ],
    philosophies: ["hard-assets", "american-fortress", "abundance"],
    policy: { climate: 0.1, defense: 0.15, trade: 0.2, techReg: 0, china: 0.25, rates: -0.1 },
    buffett: {
      moat: 4,
      understandability: 4,
      quality: 4,
      note: "Dealer network, parts, and a brand on a job site.",
    },
    damodaran: {
      story: "Capex cycles in mining, energy, and construction.",
      risk: "A late-cycle industrial wearing a reshoring story.",
    },
  },
  {
    ticker: "DE",
    name: "Deere",
    sector: "Industrials",
    geography: "United States",
    summary: "Farm equipment with a software ambition and a political constituency.",
    narratives: [
      { id: "reindustrialization", weight: 0.35 },
      { id: "us-exceptionalism", weight: 0.3 },
      { id: "commodity-cycle", weight: 0.2 },
      { id: "software-subscription", weight: 0.15 },
    ],
    philosophies: ["hard-assets", "moat-compounder", "american-fortress"],
    policy: { climate: 0.15, defense: 0, trade: 0.15, techReg: 0.1, china: 0.1, rates: 0.15 },
    buffett: {
      moat: 4,
      understandability: 4,
      quality: 4,
      note: "A franchise farmers already know how to hate and still buy.",
    },
    damodaran: {
      story: "Precision agriculture turns iron into a network.",
      risk: "Farm income is still the independent variable.",
    },
  },
  {
    ticker: "LMT",
    name: "Lockheed Martin",
    sector: "Industrials",
    geography: "United States",
    summary: "A prime contractor on the American security state.",
    narratives: [
      { id: "defense-multipolar", weight: 0.75 },
      { id: "us-exceptionalism", weight: 0.25 },
    ],
    philosophies: ["american-fortress", "industrial-policy"],
    policy: { climate: 0, defense: 0.9, trade: -0.15, techReg: 0, china: -0.4, rates: 0.05 },
    buffett: {
      moat: 4,
      understandability: 3,
      quality: 4,
      note: "A customer concentration problem named Congress.",
    },
    damodaran: {
      story: "A more dangerous world is a budget.",
      risk: "Procurement and politics are the same risk.",
    },
  },
  {
    ticker: "RTX",
    name: "RTX",
    sector: "Industrials",
    geography: "United States",
    summary: "Engines, missiles, and the aftermarket of conflict and air travel.",
    narratives: [
      { id: "defense-multipolar", weight: 0.6 },
      { id: "us-exceptionalism", weight: 0.25 },
      { id: "reindustrialization", weight: 0.15 },
    ],
    philosophies: ["american-fortress", "industrial-policy"],
    policy: { climate: 0.05, defense: 0.8, trade: 0.1, techReg: 0, china: -0.2, rates: 0.1 },
    buffett: {
      moat: 4,
      understandability: 3,
      quality: 4,
      note: "Installed base in engines is a real annuity. Missiles are the other story.",
    },
    damodaran: {
      story: "Commercial aerospace plus a hotter map.",
      risk: "Two demand curves that do not always move together.",
    },
  },
  {
    ticker: "KO",
    name: "Coca-Cola",
    sector: "Consumer",
    geography: "United States",
    summary: "Sugar water, bottlers, and a century of brand compounding.",
    narratives: [
      { id: "consumer-brand", weight: 0.7 },
      { id: "us-exceptionalism", weight: 0.2 },
      { id: "china-coupling", weight: 0.1 },
    ],
    philosophies: ["moat-compounder", "global-consumer"],
    policy: { climate: 0.05, defense: 0, trade: 0.4, techReg: 0, china: 0.25, rates: 0.1 },
    buffett: {
      moat: 5,
      understandability: 5,
      quality: 5,
      note: "The canonical wonderful business. Time does the work.",
    },
    damodaran: {
      story: "Volume, pricing, and emerging thirst.",
      risk: "A mature story. You mostly pay for the comfort of the story.",
    },
  },
  {
    ticker: "COST",
    name: "Costco",
    sector: "Consumer",
    geography: "United States",
    summary: "Membership, treasure hunts, and a cult of the $1.50 hot dog.",
    narratives: [
      { id: "consumer-brand", weight: 0.55 },
      { id: "us-exceptionalism", weight: 0.35 },
      { id: "china-coupling", weight: 0.1 },
    ],
    philosophies: ["moat-compounder", "global-consumer"],
    policy: { climate: 0, defense: 0, trade: 0.45, techReg: 0, china: 0.2, rates: 0.1 },
    buffett: {
      moat: 5,
      understandability: 5,
      quality: 5,
      note: "Trust as a moat. The membership fee is the tell.",
    },
    damodaran: {
      story: "Traffic and wallet share keep compounding.",
      risk: "A great business that the market already knows is great.",
    },
  },
  {
    ticker: "WMT",
    name: "Walmart",
    sector: "Consumer",
    geography: "United States",
    summary: "The American price level, with e-commerce bolted on.",
    narratives: [
      { id: "consumer-brand", weight: 0.4 },
      { id: "us-exceptionalism", weight: 0.4 },
      { id: "china-coupling", weight: 0.2 },
    ],
    philosophies: ["global-consumer", "moat-compounder", "american-fortress"],
    policy: { climate: 0.05, defense: 0, trade: 0.55, techReg: 0.1, china: 0.4, rates: 0.05 },
    buffett: {
      moat: 4,
      understandability: 5,
      quality: 4,
      note: "Scale in the one business everyone understands: selling stuff cheaper.",
    },
    damodaran: {
      story: "US consumer plus digital catch-up.",
      risk: "Trade policy hits the cost of goods before it hits the slogan.",
    },
  },
  {
    ticker: "PG",
    name: "Procter & Gamble",
    sector: "Consumer",
    geography: "United States",
    summary: "Soap, diapers, and the quiet compounding of household habit.",
    narratives: [
      { id: "consumer-brand", weight: 0.75 },
      { id: "us-exceptionalism", weight: 0.15 },
      { id: "china-coupling", weight: 0.1 },
    ],
    philosophies: ["moat-compounder", "global-consumer"],
    policy: { climate: 0.05, defense: 0, trade: 0.35, techReg: 0, china: 0.25, rates: 0.1 },
    buffett: {
      moat: 5,
      understandability: 5,
      quality: 5,
      note: "Brands in the bathroom cabinet. The opposite of a narrative stock.",
    },
    damodaran: {
      story: "Pricing power in staples.",
      risk: "Steady stories get overpaid in nervous markets.",
    },
  },
  {
    ticker: "MCD",
    name: "McDonald's",
    sector: "Consumer",
    geography: "United States",
    summary: "Real estate, royalties, and a global habit at lunch.",
    narratives: [
      { id: "consumer-brand", weight: 0.65 },
      { id: "us-exceptionalism", weight: 0.2 },
      { id: "china-coupling", weight: 0.15 },
    ],
    philosophies: ["moat-compounder", "global-consumer", "financialization"],
    policy: { climate: 0.05, defense: 0, trade: 0.3, techReg: 0, china: 0.25, rates: 0.2 },
    buffett: {
      moat: 5,
      understandability: 5,
      quality: 5,
      note: "A franchise machine. You are buying the system, not the fries.",
    },
    damodaran: {
      story: "Asset-light royalties on a global brand.",
      risk: "Wage and calorie politics can nibble the story without killing it.",
    },
  },
  {
    ticker: "JPM",
    name: "JPMorgan Chase",
    sector: "Financials",
    geography: "United States",
    summary: "The indispensable American bank in almost any regime.",
    narratives: [
      { id: "us-exceptionalism", weight: 0.55 },
      { id: "payments-rails", weight: 0.45 },
    ],
    philosophies: ["financialization", "american-fortress", "moat-compounder"],
    policy: { climate: 0.05, defense: 0.1, trade: 0.2, techReg: 0.1, china: 0.1, rates: -0.35 },
    buffett: {
      moat: 4,
      understandability: 3,
      quality: 4,
      note: "A fortress balance sheet. Still a leveraged faith in the US cycle.",
    },
    damodaran: {
      story: "Share of US financial gravity.",
      risk: "Regulation and credit are the two silent partners.",
    },
  },
  {
    ticker: "BRK.B",
    name: "Berkshire Hathaway",
    sector: "Financials",
    geography: "United States",
    summary: "The meta-holding: insurance float, operating companies, and a philosophy.",
    narratives: [
      { id: "us-exceptionalism", weight: 0.4 },
      { id: "consumer-brand", weight: 0.2 },
      { id: "fossil-endurance", weight: 0.15 },
      { id: "payments-rails", weight: 0.15 },
      { id: "ai-platform", weight: 0.1 },
    ],
    philosophies: ["moat-compounder", "american-fortress", "hard-assets"],
    policy: { climate: -0.15, defense: 0.05, trade: 0.15, techReg: 0.15, china: 0.1, rates: 0.05 },
    buffett: {
      moat: 5,
      understandability: 4,
      quality: 5,
      note: "The house philosophy, bundled. Succession is now part of the story.",
    },
    damodaran: {
      story: "A collection of cash engines, not a single narrative.",
      risk: "A closed-end fund of America trading at a personality premium.",
    },
  },
  {
    ticker: "V",
    name: "Visa",
    sector: "Financials",
    geography: "United States",
    summary: "A toll on other people's spending.",
    narratives: [
      { id: "payments-rails", weight: 0.75 },
      { id: "us-exceptionalism", weight: 0.15 },
      { id: "consumer-brand", weight: 0.1 },
    ],
    philosophies: ["financialization", "moat-compounder"],
    policy: { climate: 0, defense: 0, trade: 0.3, techReg: 0.45, china: 0.05, rates: 0.15 },
    buffett: {
      moat: 5,
      understandability: 4,
      quality: 5,
      note: "No inventory, no factories, a network. Almost indecently Buffett.",
    },
    damodaran: {
      story: "Cash keeps dying; Visa keeps the rake.",
      risk: "Interchange regulation is the political haircut.",
    },
  },
  {
    ticker: "MA",
    name: "Mastercard",
    sector: "Financials",
    geography: "United States",
    summary: "The other tollbooth on the same highway.",
    narratives: [
      { id: "payments-rails", weight: 0.75 },
      { id: "us-exceptionalism", weight: 0.15 },
      { id: "consumer-brand", weight: 0.1 },
    ],
    philosophies: ["financialization", "moat-compounder"],
    policy: { climate: 0, defense: 0, trade: 0.3, techReg: 0.45, china: 0.05, rates: 0.15 },
    buffett: {
      moat: 5,
      understandability: 4,
      quality: 5,
      note: "Same castle, slightly different flag.",
    },
    damodaran: {
      story: "Global volume, especially outside the US.",
      risk: "Owning both Visa and Mastercard is one story, two tickers.",
    },
  },
  {
    ticker: "AXP",
    name: "American Express",
    sector: "Financials",
    geography: "United States",
    summary: "A closed-loop brand for people who like to be seen spending.",
    narratives: [
      { id: "payments-rails", weight: 0.45 },
      { id: "consumer-brand", weight: 0.35 },
      { id: "us-exceptionalism", weight: 0.2 },
    ],
    philosophies: ["moat-compounder", "financialization", "global-consumer"],
    policy: { climate: 0, defense: 0, trade: 0.2, techReg: 0.2, china: 0.1, rates: -0.1 },
    buffett: {
      moat: 5,
      understandability: 4,
      quality: 5,
      note: "Buffett's own circle of competence, repeatedly.",
    },
    damodaran: {
      story: "Premium spend and brand survive most cycles.",
      risk: "Consumer credit is still in the mix, unlike pure networks.",
    },
  },
  {
    ticker: "UNH",
    name: "UnitedHealth",
    sector: "Healthcare",
    geography: "United States",
    summary: "Insurance, clinics, and the American way of paying for care.",
    narratives: [
      { id: "healthcare-aging", weight: 0.7 },
      { id: "us-exceptionalism", weight: 0.3 },
    ],
    philosophies: ["moat-compounder", "american-fortress", "financialization"],
    policy: { climate: 0, defense: 0, trade: 0, techReg: 0.1, china: 0, rates: 0.1 },
    buffett: {
      moat: 4,
      understandability: 2,
      quality: 4,
      note: "A cash engine wrapped in a statute. Understand the statute.",
    },
    damodaran: {
      story: "Demography plus managed care scale.",
      risk: "Washington can reprice the entire model in a session.",
    },
  },
  {
    ticker: "LLY",
    name: "Eli Lilly",
    sector: "Healthcare",
    geography: "United States",
    summary: "GLP-1 as a platform, plus the rest of a drug company.",
    narratives: [
      { id: "healthcare-aging", weight: 0.65 },
      { id: "us-exceptionalism", weight: 0.2 },
      { id: "cheap-money-duration", weight: 0.15 },
    ],
    philosophies: ["moat-compounder", "abundance", "tech-optimism"],
    policy: { climate: 0, defense: 0, trade: 0.15, techReg: 0.1, china: 0.1, rates: 0.3 },
    buffett: {
      moat: 4,
      understandability: 2,
      quality: 5,
      note: "Patent cliffs are the opposite of a perpetual brand.",
    },
    damodaran: {
      story: "Obesity drugs become a franchise, not a spike.",
      risk: "One therapeutic class is doing too much of the valuation work.",
    },
  },
  {
    ticker: "JNJ",
    name: "Johnson & Johnson",
    sector: "Healthcare",
    geography: "United States",
    summary: "A diversified health conglomerate after shedding the consumer skin.",
    narratives: [
      { id: "healthcare-aging", weight: 0.7 },
      { id: "us-exceptionalism", weight: 0.2 },
      { id: "consumer-brand", weight: 0.1 },
    ],
    philosophies: ["moat-compounder", "global-consumer"],
    policy: { climate: 0, defense: 0, trade: 0.2, techReg: 0, china: 0.15, rates: 0.1 },
    buffett: {
      moat: 4,
      understandability: 3,
      quality: 4,
      note: "A collection of health cash flows. Litigation is part of the history.",
    },
    damodaran: {
      story: "Pharma plus medtech, less drama than a single-drug story.",
      risk: "Steady can be a synonym for fully priced.",
    },
  },
  {
    ticker: "NVO",
    name: "Novo Nordisk",
    sector: "Healthcare",
    geography: "Denmark",
    summary: "The other GLP-1 giant, from a smaller country with a larger story.",
    narratives: [
      { id: "healthcare-aging", weight: 0.7 },
      { id: "cheap-money-duration", weight: 0.2 },
      { id: "consumer-brand", weight: 0.1 },
    ],
    philosophies: ["moat-compounder", "abundance"],
    policy: { climate: 0, defense: 0, trade: 0.2, techReg: 0.05, china: 0.15, rates: 0.3 },
    buffett: {
      moat: 4,
      understandability: 2,
      quality: 5,
      note: "A wonderful product. Country and capacity are the unpriced footnotes.",
    },
    damodaran: {
      story: "Metabolic disease as a multi-decade market.",
      risk: "Owning Lilly and Novo is one medical story, two flags.",
    },
  },
  {
    ticker: "FCX",
    name: "Freeport-McMoRan",
    sector: "Materials",
    geography: "United States",
    summary: "Copper as electrification, and copper as a mine in a hard place.",
    narratives: [
      { id: "commodity-cycle", weight: 0.5 },
      { id: "energy-transition", weight: 0.3 },
      { id: "reindustrialization", weight: 0.2 },
    ],
    philosophies: ["hard-assets", "abundance", "industrial-policy"],
    policy: { climate: 0.45, defense: 0.15, trade: 0.15, techReg: 0, china: 0.35, rates: -0.15 },
    buffett: {
      moat: 2,
      understandability: 3,
      quality: 3,
      note: "A hole in the ground with geopolitical adjectives.",
    },
    damodaran: {
      story: "The energy transition is a metals story pretending to be a climate story.",
      risk: "China still clears the copper market.",
    },
  },
  {
    ticker: "NEM",
    name: "Newmont",
    sector: "Materials",
    geography: "United States",
    summary: "Gold in the ground for people who do not trust the paper.",
    narratives: [
      { id: "commodity-cycle", weight: 0.7 },
      { id: "us-exceptionalism", weight: 0.15 },
      { id: "cheap-money-duration", weight: 0.15 },
    ],
    philosophies: ["hard-assets"],
    policy: { climate: 0.05, defense: 0.2, trade: 0.05, techReg: 0, china: 0.1, rates: 0.25 },
    buffett: {
      moat: 1,
      understandability: 4,
      quality: 2,
      note: "Buffett has rarely loved gold. It is a belief about money, not a business.",
    },
    damodaran: {
      story: "Monetary distrust as a cash-flow story.",
      risk: "A hedge that can fail as an operating company.",
    },
  },
  {
    ticker: "BABA",
    name: "Alibaba",
    sector: "Consumer",
    geography: "China",
    summary: "China's commerce and cloud, with the state as a silent shareholder.",
    narratives: [
      { id: "china-coupling", weight: 0.7 },
      { id: "consumer-brand", weight: 0.15 },
      { id: "software-subscription", weight: 0.15 },
    ],
    philosophies: ["global-consumer", "tech-optimism"],
    policy: { climate: 0, defense: -0.1, trade: 0.4, techReg: -0.2, china: 0.9, rates: 0.2 },
    buffett: {
      moat: 3,
      understandability: 2,
      quality: 3,
      note: "A business you can like and a political system you must underwrite.",
    },
    damodaran: {
      story: "Chinese consumption and cloud, at a discount for governance.",
      risk: "Country risk is not a footnote. It is the model.",
    },
  },
  {
    ticker: "TM",
    name: "Toyota",
    sector: "Consumer",
    geography: "Japan",
    summary: "Hybrids, factories, and a slower-transition industrial view.",
    narratives: [
      { id: "consumer-brand", weight: 0.35 },
      { id: "fossil-endurance", weight: 0.25 },
      { id: "reindustrialization", weight: 0.25 },
      { id: "energy-transition", weight: 0.15 },
    ],
    philosophies: ["moat-compounder", "hard-assets", "global-consumer"],
    policy: { climate: 0.15, defense: 0.1, trade: 0.4, techReg: 0, china: 0.3, rates: 0.05 },
    buffett: {
      moat: 4,
      understandability: 4,
      quality: 4,
      note: "Operational excellence you can visit. The EV timing is the argument.",
    },
    damodaran: {
      story: "Hybrids as the adult path through the transition.",
      risk: "Being right too early looks like being wrong.",
    },
  },
  {
    ticker: "PLD",
    name: "Prologis",
    sector: "Real Estate",
    geography: "United States",
    summary: "Warehouses as the physical internet.",
    narratives: [
      { id: "reindustrialization", weight: 0.35 },
      { id: "us-exceptionalism", weight: 0.3 },
      { id: "cheap-money-duration", weight: 0.35 },
    ],
    philosophies: ["hard-assets", "financialization", "abundance"],
    policy: { climate: 0.1, defense: 0.05, trade: 0.35, techReg: 0, china: 0.1, rates: 0.75 },
    buffett: {
      moat: 3,
      understandability: 4,
      quality: 3,
      note: "Location is a moat until the cap rate moves.",
    },
    damodaran: {
      story: "Logistics real estate compounds with trade and e-commerce.",
      risk: "A rates story wearing a warehouses costume.",
    },
  },
  {
    ticker: "NFLX",
    name: "Netflix",
    sector: "Communication",
    geography: "United States",
    summary: "A global attention subscription, now with ads.",
    narratives: [
      { id: "consumer-brand", weight: 0.45 },
      { id: "software-subscription", weight: 0.3 },
      { id: "us-exceptionalism", weight: 0.15 },
      { id: "cheap-money-duration", weight: 0.1 },
    ],
    philosophies: ["tech-optimism", "global-consumer", "moat-compounder"],
    policy: { climate: 0, defense: 0, trade: 0.25, techReg: 0.3, china: 0.05, rates: 0.35 },
    buffett: {
      moat: 3,
      understandability: 4,
      quality: 3,
      note: "Habit is a moat until a new feed appears.",
    },
    damodaran: {
      story: "Pricing power after the land-grab.",
      risk: "Content spend is the hidden capital intensity.",
    },
  },
];

export const COMPANY_BY_TICKER = Object.fromEntries(
  COMPANIES.map((company) => [company.ticker, company]),
) as Record<string, Company>;
